### ISSUE TITLE
VSCode not recognizing the configuration

### ISSUE THREAD

**Issue by slomek** [blackdahila/go-group-imports-vscode#1]
## What I did
Downloaded the plugin and reloaded VSCode to activate it.

## What I expected
Have Go imports grouped on save.

## What happenned
Nothing, really. I've added the configuration setting explicitly in my `settings.json` and it started working. The weird thing was that VSCode didn't recognize the configuration even though, see screenshot.
<img width="220" alt="unknown-configuration-setting" src="https://user-images.githubusercontent.com/4399871/47363456-24e37800-d6d7-11e8-8683-1ce2a78874e6.png">

**Comment by blackdahila** [comment]
There was a bug in package.json. It's already fixed.
