### ISSUE TITLE
Please add a LICENSE

### ISSUE THREAD

**Issue by johnaoss** [blackdahila/go-group-imports-vscode#6]
Could you please add an explicit LICENSE file to the repo so that it's clear under what terms the content is provided, and under what terms user contributions are licensed?

Per [GitHub's Open Source Guide on licensing](https://opensource.guide/legal/):

> [...] the law assumes that as the author of your work, you have a say in what others can do with it. In general, that means nobody else can use, copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation.

> If you don’t apply an open source license, everybody who contributes to your project also becomes an exclusive copyright holder of their work. That means nobody can use, copy, distribute, or modify their contributions – and that “nobody” includes you.

If you need help choosing a licence, [choosealicense.com](https://choosealicense.com) is a good resource to find a license that suits your needs. If you can't decide on one, the [MIT License](https://choosealicense.com/licenses/mit) is a good, permissive default!

Thanks!

**Comment by blackdahila** [comment]
Done 🙂

**Comment by johnaoss** [comment]
Thank you very much! 🎉
